# ==== disable single 'q' ====
[[mgr.prepend_keymap]]
on  = ["q"]          # 単発 q
run = "noop"         # 既定の quit を無効化
desc = "Disable single q quit"

# ==== quit with confirmation on 'q','q' ====
[[mgr.prepend_keymap]]
on  = ["q","q"]      # 連続 qq
run = "quit"
desc = "Quit Yazi (qq)"

# Enterでファイルを開く（MacVimなど）
[[keymap.normal]]
on = ["enter"]
run = "open"
desc = "Open selected"

# Shift+OでFinderを開く
[[mgr.prepend_keymap]]
on   = "O"
run  = 'shell -- open "$0"'
desc = "Open hovered in Finder"


# デフォルトより先にマッピングを差し込む
[[mgr.prepend_keymap]]
on  = ["\\", "y"]
run = 'shell -- cat "$0" | pbcopy'
desc = "ファイルの内容をクリップボードにコピー"

[[mgr.prepend_keymap]]
on  = ["g", "f"]
run = 'cd ~/dotfiles'
desc = "Go ~/dotfiles"

[[mgr.prepend_keymap]]
on  = ["g", "m"]
run = 'cd ~/memo-arai'
desc = "Go ~/memo-arai"

[[mgr.prepend_keymap]]
on  = ["g", "u"]
run = 'cd ~/uc'
desc = "Go ~/uc"

