# ==== disable single 'q' ====
[[mgr.prepend_keymap]]
on  = ["q"]          # 単発 q
run = "noop"         # 既定の quit を無効化
desc = "Disable single q quit"

# ==== quit with confirmation on 'q','q' ====
[[mgr.prepend_keymap]]
on  = ["q","q"]      # 連続 qq
run = "quit"
desc = "Quit Yazi (qq)"

# Enterでファイルを開く（MacVimなど）
[[keymap.normal]]
on = ["enter"]
run = "open"
desc = "Open selected"

# Shift+OでFinderを開く
[[mgr.prepend_keymap]]
on   = "O"
run  = 'shell -- open "$0"'
desc = "Open hovered in Finder"


# デフォルトより先にマッピングを差し込む
[[mgr.prepend_keymap]]
on  = ["\\", "y"]
run = 'shell -- cat "$0" | pbcopy'
desc = "ファイルの内容をクリップボードにコピー"

[[mgr.prepend_keymap]]
on  = ["g", "f"]
run = 'cd ~/dotfiles'
desc = "Go ~/dotfiles"

[[mgr.prepend_keymap]]
on  = ["g", "m"]
run = 'cd ~/memo-arai'
desc = "Go ~/memo-arai"

[[mgr.prepend_keymap]]
on  = ["g", "u"]
run = 'cd ~/uc'
desc = "Go ~/uc"

# \v : 行番号なしで色付きビュー
[[mgr.prepend_keymap]]
on   = ["\\", "v"]
run  = '''
shell --block -- bash -lc "bat --paging=always --style=plain \"$0\""
'''
desc = "View (bat, no numbers)"

# \V : 行番号あり
[[mgr.prepend_keymap]]
on   = ["\\", "V"]
run  = '''
shell --block -- bash -lc "bat --paging=always --style=numbers \"$0\""
'''
desc = "View (bat, with numbers)"

# /m : 既存ウィンドウがあればタブに追加
[[mgr.prepend_keymap]]
on   = ["\\", "m"]
run  = '''
shell -- /Applications/MacVim.app/Contents/bin/mvim --remote-tab-silent "$0" || /Applications/MacVim.app/Contents/bin/mvim "$0"
'''
desc = "Open in MacVim (reuse window tab)"

# /M : 常に新しいウィンドウで開く
[[mgr.prepend_keymap]]
on   = ["\\", "M"]
run  = '''
shell -- /Applications/MacVim.app/Contents/bin/mvim -f "$0"
'''
desc = "Open in MacVim (new window)"

