[mgr]
# show_hidden = true           # ドットファイルを表示
# ↑
# .をタイプすることでドットファイルの表示非表示ができるためコメントアウト
# sort_by = "mtime"            # 更新日時でソート
# sort_reverse = true          # 新しい順に表示
sort_by = "natural"       # 名前順でソート
sort_reverse = false   # 昇順（A→Z）
scroll_offset = 3            # スクロール余白
case_sensitive = false       # 大文字小文字を区別しない
linemode = "size"            # ファイルサイズを右側に表示
show_symlink = true          # シンボリックリンクを表示
show_git = true              # Gitステータス表示（Rust拡張が必要）
xdg_open = true              # macOSの「open」コマンドで開ける
ratio = [1, 2, 8] # 「左・中央・右」ペインの比率

[preview]
# wrap = "yes"                 # 長い行を折り返す
# max_width = 999
# max_height = 300
image_quality = 85
tab_size = 2
image_downscale = true

# ここがポイント：バイナリ系はプレビュー無効化
disable = [
  "audio/*",
  "application/octet-stream"  # 拡張子不明のバイナリ保険
]

[opener]
macvim = [
  # GUIで開く & yaziから切り離す
  { run = 'open -a "MacVim" "$1"', desc = "Open in MacVim", orphan = true, for = "macos" }
]
vim = [
  { run = 'vim "$1"', desc = "Edit in terminal Vim", block = true, for = "unix" }
]
open = [
  # macOSのデフォルトアプリで開く（画像/動画/PDFなど）
  { run = 'open "$1"', desc = "Open with macOS default app", orphan = true, for = "macos" }
]
edit = [
  # 端末Vimで開きたいとき用（任意）
  { run = 'vim "$1"', desc = "Edit in terminal Vim", block = true, for = "unix" }
]

[open]
rules = [
  { name = "*.txt", use = "vim" },
  { name = "*.toml", use = "vim" },
  { name = "*.json", use = "vim" },
  { name = "*.yaml", use = "vim" },
  { name = "*.yml", use = "vim" },
  { mime = "application/x-empty", use = "vim" },
  { mime = "text/*", use = "vim" },

  # 画像/メディア/PDF は macOS のデフォルトアプリ
  { mime = "image/*", use = "open" },
  { mime = "video/*", use = "open" },
  { mime = "audio/*", use = "open" },
  { mime = "application/pdf", use = "open" },

  # なんでも最後はデフォルトへ
  { name = "*", use = "open" }
]

# --- PDFプレビューを完全に無効化 ---
[plugin]
# 既定よりも前に差し込む（＝優先して適用）
prepend_previewers = [
  # --- ここからシェルスクリプトの明示プレビュー ---
  { name = "*.sh",   run = "code" },
  { name = "*.bash", run = "code" },
  { name = "*.zsh",  run = "code" },
  { mime = "text/x-shellscript", run = "code" },
  { mime = "application/x-sh",   run = "code" },
  { mime = "text/x-sh",          run = "code" },

  # { mime = "application/pdf", run = "noop" },
  # { mime = "image/*", run = "noop" },
  # { mime = "video/*", run = "noop" },
  # { mime = "audio/*", run = "noop" },
  # { mime = "application/octet-stream", run = "noop" }	
]
prepend_preloaders = [
  # { mime = "application/pdf", run = "noop" },
  # { mime = "image/*", run = "noop" },
  # { mime = "video/*", run = "noop" },
  # { mime = "audio/*", run = "noop" },
  # { mime = "application/octet-stream", run = "noop" }	
]

[tasks]
# 例: 幅/高さ 10000px まで許可
image_bound = [10000, 10000]

# 例: 1枚あたり 768 MiB までメモリ許可（必要なら増減）
image_alloc = 805306368

